// Code generated by Kitex v0.9.1. DO NOT EDIT.

package userservice

import (
	"context"

	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"

	user "github.com/Mutezebra/tiktok/kitex_gen/api/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error)
	Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error)
	Info(ctx context.Context, req *user.InfoReq, callOptions ...callopt.Option) (r *user.InfoResp, err error)
	UploadAvatar(ctx context.Context, req *user.UploadAvatarReq, callOptions ...callopt.Option) (r *user.UploadAvatarResp, err error)
	DownloadAvatar(ctx context.Context, req *user.DownloadAvatarReq, callOptions ...callopt.Option) (r *user.DownloadAvatarResp, err error)
	TotpQrcode(ctx context.Context, req *user.TotpQrcodeReq, callOptions ...callopt.Option) (r *user.TotpQrcodeResp, err error)
	EnableTotp(ctx context.Context, req *user.EnableTotpReq, callOptions ...callopt.Option) (r *user.EnableTotpResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) Info(ctx context.Context, req *user.InfoReq, callOptions ...callopt.Option) (r *user.InfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Info(ctx, req)
}

func (p *kUserServiceClient) UploadAvatar(ctx context.Context, req *user.UploadAvatarReq, callOptions ...callopt.Option) (r *user.UploadAvatarResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadAvatar(ctx, req)
}

func (p *kUserServiceClient) DownloadAvatar(ctx context.Context, req *user.DownloadAvatarReq, callOptions ...callopt.Option) (r *user.DownloadAvatarResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DownloadAvatar(ctx, req)
}

func (p *kUserServiceClient) TotpQrcode(ctx context.Context, req *user.TotpQrcodeReq, callOptions ...callopt.Option) (r *user.TotpQrcodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TotpQrcode(ctx, req)
}

func (p *kUserServiceClient) EnableTotp(ctx context.Context, req *user.EnableTotpReq, callOptions ...callopt.Option) (r *user.EnableTotpResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EnableTotp(ctx, req)
}
