version: "3.3"

networks:
  tiktok:
    driver: bridge

services:
  mysql:
    container_name: tiktok_mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=asodoln1ias
      - MYSQL_DATABASE=tiktok
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
    networks:
      - tiktok

  etcd:
    container_name: tiktok_etcd
    image: bitnami/etcd:latest
    restart: always
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    networks:
      - tiktok

  redis:
    container_name: tiktok_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./config/conf/redis.conf:/usr/local/etc/redis/redis.conf # password 配置也在其中
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - tiktok