version: "3.3"

networks:
  tiktok:
    driver: bridge

services:
  mysql:
    container_name: tiktok_mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=asodoln1ias
      - MYSQL_DATABASE=tiktok
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
    networks:
      - tiktok

  etcd:
    container_name: tiktok_etcd
    image: bitnami/etcd:latest
    restart: always
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    networks:
      - tiktok

  redis:
    container_name: tiktok_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./config/conf/redis.conf:/usr/local/etc/redis/redis.conf # password 配置也在其中
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - tiktok

  kafka:
    container_name: tiktok_kafka
    image: bitnami/kafka:latest
    restart: always
    user: root
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - BITNAMI_DEBUG=yes
      # 启用KRaft模式必须设置下面三个属性
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # broker id
      - KAFKA_BROKER_ID=1
      # listener的各种配置
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9094,BROKER://:9092,EXTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      # 注意EXTERNAL配置的是当前Docker所在的主机地址,BROKER可以使用Docker内部的网络地址即可
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://tiktok_kafka:9092,EXTERNAL://127.0.0.1:9093
      # 内部各个broker之间通信用的listener
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      # 用来进行选举的Controller服务器，如果有多个Controller则都需要写上，这里本机
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9094
      - ALLOW_PLAINTEXT_LISTENER=yes

    networks:
      - tiktok

  kafka-ui:
    container_name: tiktok_kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "9091:8080"
    environment:
      # 集群名称
      - KAFKA_CLUSTERS_0_NAME=single
      # 集群地址
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS= kafka:9092
    networks:
      - tiktok
