apiVersion: v1
kind: Service
metadata:
  name: tiktok-interaction-svc
spec:
  type: NodePort
  selector:
    app: tiktok-interaction-pod
  ports:
    - protocol: TCP
      port: 10003
      targetPort: 10003
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-interaction-dep
spec:
  selector:
    matchLabels:
      app: tiktok-interaction-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: tiktok-interaction-pod
    spec:
      containers:
        - name: service-interaction
          image: mutezebra/tiktok-interaction:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10003
          volumeMounts:
            - name: config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: config
          configMap:
            name: tiktok-interaction-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: logs
          persistentVolumeClaim:
            claimName: tiktok-interaction-log-pvc
