// Code generated by Kitex v0.9.1. DO NOT EDIT.

package interactionservice

import (
	"context"
	interaction "github.com/Mutezebra/tiktok/kitex_gen/api/interaction"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Like(ctx context.Context, req *interaction.LikeReq, callOptions ...callopt.Option) (r *interaction.LikeResp, err error)
	Dislike(ctx context.Context, req *interaction.DislikeReq, callOptions ...callopt.Option) (r *interaction.DislikeResp, err error)
	LikeList(ctx context.Context, req *interaction.LikeListReq, callOptions ...callopt.Option) (r *interaction.LikeListResp, err error)
	Comment(ctx context.Context, req *interaction.CommentReq, callOptions ...callopt.Option) (r *interaction.CommentResp, err error)
	CommentList(ctx context.Context, req *interaction.CommentListReq, callOptions ...callopt.Option) (r *interaction.CommentListResp, err error)
	DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq, callOptions ...callopt.Option) (r *interaction.DeleteCommentResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractionServiceClient struct {
	*kClient
}

func (p *kInteractionServiceClient) Like(ctx context.Context, req *interaction.LikeReq, callOptions ...callopt.Option) (r *interaction.LikeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Like(ctx, req)
}

func (p *kInteractionServiceClient) Dislike(ctx context.Context, req *interaction.DislikeReq, callOptions ...callopt.Option) (r *interaction.DislikeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Dislike(ctx, req)
}

func (p *kInteractionServiceClient) LikeList(ctx context.Context, req *interaction.LikeListReq, callOptions ...callopt.Option) (r *interaction.LikeListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeList(ctx, req)
}

func (p *kInteractionServiceClient) Comment(ctx context.Context, req *interaction.CommentReq, callOptions ...callopt.Option) (r *interaction.CommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Comment(ctx, req)
}

func (p *kInteractionServiceClient) CommentList(ctx context.Context, req *interaction.CommentListReq, callOptions ...callopt.Option) (r *interaction.CommentListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, req)
}

func (p *kInteractionServiceClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq, callOptions ...callopt.Option) (r *interaction.DeleteCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, req)
}
