apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
spec:
  ports:
    - port: 2379
      targetPort: 2379
  selector:
    app: etcd-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd-pod
  template:
    metadata:
      labels:
        app: etcd-pod
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:3.5.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2379
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
          volumeMounts:
            - mountPath: /bitnami/etcd
              name: etcd-data
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: etcd-pvc
