apiVersion: v1
kind: Service
metadata:
  name: jaeger-svc
  labels:
    app: jaeger-pod
spec:
  type: NodePort
  selector:
    app: jaeger-pod
  ports:
    - port: 16686
      targetPort: 16686
      nodePort: 32686
      name: jaeger-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-pod
  template:
    metadata:
      labels:
        app: jaeger-pod
    spec:
      containers:
        - name: jaeger-all-in-one
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686 # ui
              protocol: TCP
            - containerPort: 14268 # col
              protocol: TCP
            - containerPort: 14250 # col
              protocol: TCP
            - containerPort: 6831 # Agent
              protocol: UDP
            - containerPort: 6832 # Agent
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 9411
              protocol: TCP

