apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-pod
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30306
  selector:
    app: mysql-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
spec:
  selector:
    matchLabels:
      app: mysql-pod
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
        - image: mysql:latest
          imagePullPolicy: IfNotPresent
          name: mysql
          env:
            # 在实际中使用 secret
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: tiktok
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
            - name: config
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: config
          configMap:
            name: mysql-config
