apiVersion: v1
kind: Service
metadata:
  name: tiktok-user-svc
spec:
  type: NodePort
  selector:
    app: tiktok-user-pod
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-user-dep
spec:
  selector:
    matchLabels:
      app: tiktok-user-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: tiktok-user-pod
    spec:
      containers:
        - name: user
          image: mutezebra/tiktok-user:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10001
          volumeMounts:
            - name: config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: logs
              mountPath: /app/logs

      volumes:
        - name: config
          configMap:
            name: tiktok-user-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: logs
          persistentVolumeClaim:
            claimName: tiktok-user-log-pvc
