// Code generated by Kitex v0.10.1. DO NOT EDIT.

package interactionservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	interaction "github.com/mutezebra/tiktok/pkg/kitex_gen/api/interaction"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Like": kitex.NewMethodInfo(
		likeHandler,
		newInteractionServiceLikeArgs,
		newInteractionServiceLikeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Dislike": kitex.NewMethodInfo(
		dislikeHandler,
		newInteractionServiceDislikeArgs,
		newInteractionServiceDislikeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LikeList": kitex.NewMethodInfo(
		likeListHandler,
		newInteractionServiceLikeListArgs,
		newInteractionServiceLikeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Comment": kitex.NewMethodInfo(
		commentHandler,
		newInteractionServiceCommentArgs,
		newInteractionServiceCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommentList": kitex.NewMethodInfo(
		commentListHandler,
		newInteractionServiceCommentListArgs,
		newInteractionServiceCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteComment": kitex.NewMethodInfo(
		deleteCommentHandler,
		newInteractionServiceDeleteCommentArgs,
		newInteractionServiceDeleteCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	interactionServiceServiceInfo                = NewServiceInfo()
	interactionServiceServiceInfoForClient       = NewServiceInfoForClient()
	interactionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interactionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InteractionService"
	handlerType := (*interaction.InteractionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interaction",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.1",
		Extra:           extra,
	}
	return svcInfo
}

func likeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceLikeArgs)
	realResult := result.(*interaction.InteractionServiceLikeResult)
	success, err := handler.(interaction.InteractionService).Like(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceLikeArgs() interface{} {
	return interaction.NewInteractionServiceLikeArgs()
}

func newInteractionServiceLikeResult() interface{} {
	return interaction.NewInteractionServiceLikeResult()
}

func dislikeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceDislikeArgs)
	realResult := result.(*interaction.InteractionServiceDislikeResult)
	success, err := handler.(interaction.InteractionService).Dislike(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceDislikeArgs() interface{} {
	return interaction.NewInteractionServiceDislikeArgs()
}

func newInteractionServiceDislikeResult() interface{} {
	return interaction.NewInteractionServiceDislikeResult()
}

func likeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceLikeListArgs)
	realResult := result.(*interaction.InteractionServiceLikeListResult)
	success, err := handler.(interaction.InteractionService).LikeList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceLikeListArgs() interface{} {
	return interaction.NewInteractionServiceLikeListArgs()
}

func newInteractionServiceLikeListResult() interface{} {
	return interaction.NewInteractionServiceLikeListResult()
}

func commentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceCommentArgs)
	realResult := result.(*interaction.InteractionServiceCommentResult)
	success, err := handler.(interaction.InteractionService).Comment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceCommentArgs() interface{} {
	return interaction.NewInteractionServiceCommentArgs()
}

func newInteractionServiceCommentResult() interface{} {
	return interaction.NewInteractionServiceCommentResult()
}

func commentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceCommentListArgs)
	realResult := result.(*interaction.InteractionServiceCommentListResult)
	success, err := handler.(interaction.InteractionService).CommentList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceCommentListArgs() interface{} {
	return interaction.NewInteractionServiceCommentListArgs()
}

func newInteractionServiceCommentListResult() interface{} {
	return interaction.NewInteractionServiceCommentListResult()
}

func deleteCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionServiceDeleteCommentArgs)
	realResult := result.(*interaction.InteractionServiceDeleteCommentResult)
	success, err := handler.(interaction.InteractionService).DeleteComment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionServiceDeleteCommentArgs() interface{} {
	return interaction.NewInteractionServiceDeleteCommentArgs()
}

func newInteractionServiceDeleteCommentResult() interface{} {
	return interaction.NewInteractionServiceDeleteCommentResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Like(ctx context.Context, req *interaction.LikeReq) (r *interaction.LikeResp, err error) {
	var _args interaction.InteractionServiceLikeArgs
	_args.Req = req
	var _result interaction.InteractionServiceLikeResult
	if err = p.c.Call(ctx, "Like", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Dislike(ctx context.Context, req *interaction.DislikeReq) (r *interaction.DislikeResp, err error) {
	var _args interaction.InteractionServiceDislikeArgs
	_args.Req = req
	var _result interaction.InteractionServiceDislikeResult
	if err = p.c.Call(ctx, "Dislike", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LikeList(ctx context.Context, req *interaction.LikeListReq) (r *interaction.LikeListResp, err error) {
	var _args interaction.InteractionServiceLikeListArgs
	_args.Req = req
	var _result interaction.InteractionServiceLikeListResult
	if err = p.c.Call(ctx, "LikeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Comment(ctx context.Context, req *interaction.CommentReq) (r *interaction.CommentResp, err error) {
	var _args interaction.InteractionServiceCommentArgs
	_args.Req = req
	var _result interaction.InteractionServiceCommentResult
	if err = p.c.Call(ctx, "Comment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentList(ctx context.Context, req *interaction.CommentListReq) (r *interaction.CommentListResp, err error) {
	var _args interaction.InteractionServiceCommentListArgs
	_args.Req = req
	var _result interaction.InteractionServiceCommentListResult
	if err = p.c.Call(ctx, "CommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteComment(ctx context.Context, req *interaction.DeleteCommentReq) (r *interaction.DeleteCommentResp, err error) {
	var _args interaction.InteractionServiceDeleteCommentArgs
	_args.Req = req
	var _result interaction.InteractionServiceDeleteCommentResult
	if err = p.c.Call(ctx, "DeleteComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
