apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-log-pv
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/gateway/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  config.yaml: |-
    system:
      os: "linux"
      status: "debug"
      worker_id: 1
      data_center_id: 1

    service:
      gateway:
        service_name: "gateway"
        address: "0.0.0.0:4000"
      user:
        service_name: "user"
      video:
        service_name: "video"
      relation:
        service_name: "relation"
      interaction:
        service_name: "interaction"

    mysql:
      username: "root"
      password: "123456"
      address: "mysql:3306"
      database: "tiktok"
      charset: "utf8mb4"

    etcd:
      user: "tiktok"
      password: "tiktok"
      endpoint: "etcd-svc:2379"
      service_prefix: "service/"
      for_text: "text"

    kafka:
      address: "gateway-kafka-svc:9093"
      network: "tcp"

    jaeger:
      collector_endpoint: "http://jaeger-svc:14268/api/traces"
      agent_host_port: "jaeger-svc:6831"
