apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  config.yaml: |-
    system:
      os: "linux"
      status: "debug"
      worker_id: 1
      data_center_id: 1

    service:
      gateway:
        service_name: "gateway"
        address: "0.0.0.0:4000"

    mysql:
      username: "root"
      password: "123456"
      address: "mysql:3306"
      database: "tiktok"
      charset: "utf8mb4"

    etcd:
      user: "tiktok"
      password: "tiktok"
      endpoint: "etcd-svc:2379"
      service_prefix: "service/"
      for_text: "text"

    kafka:
      address: "gateway-kafka-svc:9093"
      network: "tcp"
