apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dep
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: mutezebra/tiktok-gateway:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: logs
              mountPath: /app/logs

      volumes:
        - name: config
          configMap:
            name: gateway-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: logs
          persistentVolumeClaim:
            claimName: gateway-log-pvc
