apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-kafka-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/gateway/kafka/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-kafka-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
