apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
  labels:
    app: kafka-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000 # 30000 是一个示例端口，可以在 30000-32767 范围内选择
  selector:
    app: kafka-ui

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "gateway-kafka-svc:9092"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "PLAINTEXT" # 根据 Kafka 配置的安全协议设置此值
