apiVersion: v1
kind: ConfigMap
metadata:
  name: tiktok-video-redis-cfg
data:
  redis.conf: |-
    port 6379
    bind 0.0.0.0
    requirepass tiktokpassword
    daemonize no
    loglevel notice
    logfile ""
    databases 2
    appendonly no
    save 300 10
    save 60 10000



#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: tiktok-video-redis-pv
#spec:
#  capacity:
#    storage: 2Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-path
#  local:
#    path: /data/video/redis/
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - k3s


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiktok-video-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
