apiVersion: v1
kind: Service
metadata:
  name: tiktok-video-redis-svc
spec:
  selector:
    app: tiktok-video-redis-pod
  ports:
    - name: tcp-redis-6379
      port: 6379
      protocol: TCP
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-video-redis-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiktok-video-redis-pod
  template:
    metadata:
      labels:
        app: tiktok-video-redis-pod
    spec:
      containers:
        - image: redis:6.0.8
          command: ["redis-server","/etc/redis/redis.conf"]
          name: tiktok-video-redis-pod
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: tiktok-video-redis-cfg
        - name: redis-data
          persistentVolumeClaim:
            claimName: tiktok-video-redis-pvc
