// Code generated by thriftgo (0.3.7). DO NOT EDIT.

package video

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/apache/thrift/lib/go/thrift"
)

type VideoInfo struct {
	ID        *string `thrift:"ID,1,optional" frugal:"1,optional,string" json:"id,omitempry"`
	UID       *string `thrift:"UID,2,optional" frugal:"2,optional,string" json:"uid,omitempry"`
	VideoURL  *string `thrift:"VideoURL,3,optional" frugal:"3,optional,string" json:"video_url,omitempry"`
	CoverURL  *string `thrift:"CoverURL,4,optional" frugal:"4,optional,string" json:"cover_url,omitempry"`
	Intro     *string `thrift:"Intro,5,optional" frugal:"5,optional,string" json:"intro,omitempry"`
	Title     *string `thrift:"Title,6,optional" frugal:"6,optional,string" json:"title,omitempry"`
	Starts    *int32  `thrift:"Starts,7,optional" frugal:"7,optional,i32" json:"starts,omitempry"`
	Favorites *int32  `thrift:"Favorites,8,optional" frugal:"8,optional,i32" json:"favorites,omitempry"`
	Views     *int32  `thrift:"Views,9,optional" frugal:"9,optional,i32" json:"views,omitempry"`
}

func NewVideoInfo() *VideoInfo {
	return &VideoInfo{}
}

func (p *VideoInfo) InitDefault() {
	*p = VideoInfo{}
}

var VideoInfo_ID_DEFAULT string

func (p *VideoInfo) GetID() (v string) {
	if !p.IsSetID() {
		return VideoInfo_ID_DEFAULT
	}
	return *p.ID
}

var VideoInfo_UID_DEFAULT string

func (p *VideoInfo) GetUID() (v string) {
	if !p.IsSetUID() {
		return VideoInfo_UID_DEFAULT
	}
	return *p.UID
}

var VideoInfo_VideoURL_DEFAULT string

func (p *VideoInfo) GetVideoURL() (v string) {
	if !p.IsSetVideoURL() {
		return VideoInfo_VideoURL_DEFAULT
	}
	return *p.VideoURL
}

var VideoInfo_CoverURL_DEFAULT string

func (p *VideoInfo) GetCoverURL() (v string) {
	if !p.IsSetCoverURL() {
		return VideoInfo_CoverURL_DEFAULT
	}
	return *p.CoverURL
}

var VideoInfo_Intro_DEFAULT string

func (p *VideoInfo) GetIntro() (v string) {
	if !p.IsSetIntro() {
		return VideoInfo_Intro_DEFAULT
	}
	return *p.Intro
}

var VideoInfo_Title_DEFAULT string

func (p *VideoInfo) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return VideoInfo_Title_DEFAULT
	}
	return *p.Title
}

var VideoInfo_Starts_DEFAULT int32

func (p *VideoInfo) GetStarts() (v int32) {
	if !p.IsSetStarts() {
		return VideoInfo_Starts_DEFAULT
	}
	return *p.Starts
}

var VideoInfo_Favorites_DEFAULT int32

func (p *VideoInfo) GetFavorites() (v int32) {
	if !p.IsSetFavorites() {
		return VideoInfo_Favorites_DEFAULT
	}
	return *p.Favorites
}

var VideoInfo_Views_DEFAULT int32

func (p *VideoInfo) GetViews() (v int32) {
	if !p.IsSetViews() {
		return VideoInfo_Views_DEFAULT
	}
	return *p.Views
}
func (p *VideoInfo) SetID(val *string) {
	p.ID = val
}
func (p *VideoInfo) SetUID(val *string) {
	p.UID = val
}
func (p *VideoInfo) SetVideoURL(val *string) {
	p.VideoURL = val
}
func (p *VideoInfo) SetCoverURL(val *string) {
	p.CoverURL = val
}
func (p *VideoInfo) SetIntro(val *string) {
	p.Intro = val
}
func (p *VideoInfo) SetTitle(val *string) {
	p.Title = val
}
func (p *VideoInfo) SetStarts(val *int32) {
	p.Starts = val
}
func (p *VideoInfo) SetFavorites(val *int32) {
	p.Favorites = val
}
func (p *VideoInfo) SetViews(val *int32) {
	p.Views = val
}

var fieldIDToName_VideoInfo = map[int16]string{
	1: "ID",
	2: "UID",
	3: "VideoURL",
	4: "CoverURL",
	5: "Intro",
	6: "Title",
	7: "Starts",
	8: "Favorites",
	9: "Views",
}

func (p *VideoInfo) IsSetID() bool {
	return p.ID != nil
}

func (p *VideoInfo) IsSetUID() bool {
	return p.UID != nil
}

func (p *VideoInfo) IsSetVideoURL() bool {
	return p.VideoURL != nil
}

func (p *VideoInfo) IsSetCoverURL() bool {
	return p.CoverURL != nil
}

func (p *VideoInfo) IsSetIntro() bool {
	return p.Intro != nil
}

func (p *VideoInfo) IsSetTitle() bool {
	return p.Title != nil
}

func (p *VideoInfo) IsSetStarts() bool {
	return p.Starts != nil
}

func (p *VideoInfo) IsSetFavorites() bool {
	return p.Favorites != nil
}

func (p *VideoInfo) IsSetViews() bool {
	return p.Views != nil
}

func (p *VideoInfo) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 8:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 9:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField9(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_VideoInfo[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *VideoInfo) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.ID = &v
	}
	return nil
}
func (p *VideoInfo) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.UID = &v
	}
	return nil
}
func (p *VideoInfo) ReadField3(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.VideoURL = &v
	}
	return nil
}
func (p *VideoInfo) ReadField4(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.CoverURL = &v
	}
	return nil
}
func (p *VideoInfo) ReadField5(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Intro = &v
	}
	return nil
}
func (p *VideoInfo) ReadField6(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Title = &v
	}
	return nil
}
func (p *VideoInfo) ReadField7(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Starts = &v
	}
	return nil
}
func (p *VideoInfo) ReadField8(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Favorites = &v
	}
	return nil
}
func (p *VideoInfo) ReadField9(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Views = &v
	}
	return nil
}

func (p *VideoInfo) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("VideoInfo"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}
		if err = p.writeField9(oprot); err != nil {
			fieldId = 9
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *VideoInfo) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetID() {
		if err = oprot.WriteFieldBegin("ID", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *VideoInfo) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetUID() {
		if err = oprot.WriteFieldBegin("UID", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.UID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *VideoInfo) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetVideoURL() {
		if err = oprot.WriteFieldBegin("VideoURL", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.VideoURL); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *VideoInfo) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCoverURL() {
		if err = oprot.WriteFieldBegin("CoverURL", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.CoverURL); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *VideoInfo) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetIntro() {
		if err = oprot.WriteFieldBegin("Intro", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Intro); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *VideoInfo) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetTitle() {
		if err = oprot.WriteFieldBegin("Title", thrift.STRING, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Title); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *VideoInfo) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetStarts() {
		if err = oprot.WriteFieldBegin("Starts", thrift.I32, 7); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Starts); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *VideoInfo) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetFavorites() {
		if err = oprot.WriteFieldBegin("Favorites", thrift.I32, 8); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Favorites); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}

func (p *VideoInfo) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetViews() {
		if err = oprot.WriteFieldBegin("Views", thrift.I32, 9); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Views); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 end error: ", p), err)
}

func (p *VideoInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoInfo(%+v)", *p)

}

func (p *VideoInfo) DeepEqual(ano *VideoInfo) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.ID) {
		return false
	}
	if !p.Field2DeepEqual(ano.UID) {
		return false
	}
	if !p.Field3DeepEqual(ano.VideoURL) {
		return false
	}
	if !p.Field4DeepEqual(ano.CoverURL) {
		return false
	}
	if !p.Field5DeepEqual(ano.Intro) {
		return false
	}
	if !p.Field6DeepEqual(ano.Title) {
		return false
	}
	if !p.Field7DeepEqual(ano.Starts) {
		return false
	}
	if !p.Field8DeepEqual(ano.Favorites) {
		return false
	}
	if !p.Field9DeepEqual(ano.Views) {
		return false
	}
	return true
}

func (p *VideoInfo) Field1DeepEqual(src *string) bool {

	if p.ID == src {
		return true
	} else if p.ID == nil || src == nil {
		return false
	}
	if strings.Compare(*p.ID, *src) != 0 {
		return false
	}
	return true
}
func (p *VideoInfo) Field2DeepEqual(src *string) bool {

	if p.UID == src {
		return true
	} else if p.UID == nil || src == nil {
		return false
	}
	if strings.Compare(*p.UID, *src) != 0 {
		return false
	}
	return true
}
func (p *VideoInfo) Field3DeepEqual(src *string) bool {

	if p.VideoURL == src {
		return true
	} else if p.VideoURL == nil || src == nil {
		return false
	}
	if strings.Compare(*p.VideoURL, *src) != 0 {
		return false
	}
	return true
}
func (p *VideoInfo) Field4DeepEqual(src *string) bool {

	if p.CoverURL == src {
		return true
	} else if p.CoverURL == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CoverURL, *src) != 0 {
		return false
	}
	return true
}
func (p *VideoInfo) Field5DeepEqual(src *string) bool {

	if p.Intro == src {
		return true
	} else if p.Intro == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Intro, *src) != 0 {
		return false
	}
	return true
}
func (p *VideoInfo) Field6DeepEqual(src *string) bool {

	if p.Title == src {
		return true
	} else if p.Title == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Title, *src) != 0 {
		return false
	}
	return true
}
func (p *VideoInfo) Field7DeepEqual(src *int32) bool {

	if p.Starts == src {
		return true
	} else if p.Starts == nil || src == nil {
		return false
	}
	if *p.Starts != *src {
		return false
	}
	return true
}
func (p *VideoInfo) Field8DeepEqual(src *int32) bool {

	if p.Favorites == src {
		return true
	} else if p.Favorites == nil || src == nil {
		return false
	}
	if *p.Favorites != *src {
		return false
	}
	return true
}
func (p *VideoInfo) Field9DeepEqual(src *int32) bool {

	if p.Views == src {
		return true
	} else if p.Views == nil || src == nil {
		return false
	}
	if *p.Views != *src {
		return false
	}
	return true
}

type VideoFeedReq struct {
	UID *int64 `thrift:"UID,1,optional" frugal:"1,optional,i64" json:"UID,omitempty"`
	VID *int64 `thrift:"VID,2,optional" frugal:"2,optional,i64" form:"vid,required"`
}

func NewVideoFeedReq() *VideoFeedReq {
	return &VideoFeedReq{}
}

func (p *VideoFeedReq) InitDefault() {
	*p = VideoFeedReq{}
}

var VideoFeedReq_UID_DEFAULT int64

func (p *VideoFeedReq) GetUID() (v int64) {
	if !p.IsSetUID() {
		return VideoFeedReq_UID_DEFAULT
	}
	return *p.UID
}

var VideoFeedReq_VID_DEFAULT int64

func (p *VideoFeedReq) GetVID() (v int64) {
	if !p.IsSetVID() {
		return VideoFeedReq_VID_DEFAULT
	}
	return *p.VID
}
func (p *VideoFeedReq) SetUID(val *int64) {
	p.UID = val
}
func (p *VideoFeedReq) SetVID(val *int64) {
	p.VID = val
}

var fieldIDToName_VideoFeedReq = map[int16]string{
	1: "UID",
	2: "VID",
}

func (p *VideoFeedReq) IsSetUID() bool {
	return p.UID != nil
}

func (p *VideoFeedReq) IsSetVID() bool {
	return p.VID != nil
}

func (p *VideoFeedReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_VideoFeedReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *VideoFeedReq) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.UID = &v
	}
	return nil
}
func (p *VideoFeedReq) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.VID = &v
	}
	return nil
}

func (p *VideoFeedReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("VideoFeedReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *VideoFeedReq) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetUID() {
		if err = oprot.WriteFieldBegin("UID", thrift.I64, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.UID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *VideoFeedReq) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetVID() {
		if err = oprot.WriteFieldBegin("VID", thrift.I64, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.VID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *VideoFeedReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoFeedReq(%+v)", *p)

}

func (p *VideoFeedReq) DeepEqual(ano *VideoFeedReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UID) {
		return false
	}
	if !p.Field2DeepEqual(ano.VID) {
		return false
	}
	return true
}

func (p *VideoFeedReq) Field1DeepEqual(src *int64) bool {

	if p.UID == src {
		return true
	} else if p.UID == nil || src == nil {
		return false
	}
	if *p.UID != *src {
		return false
	}
	return true
}
func (p *VideoFeedReq) Field2DeepEqual(src *int64) bool {

	if p.VID == src {
		return true
	} else if p.VID == nil || src == nil {
		return false
	}
	if *p.VID != *src {
		return false
	}
	return true
}

type VideoFeedResp struct {
	Count *int32       `thrift:"Count,1,optional" frugal:"1,optional,i32" json:"count,omitempry"`
	Items []*VideoInfo `thrift:"items,2,optional" frugal:"2,optional,list<VideoInfo>" json:"items,omitempry"`
}

func NewVideoFeedResp() *VideoFeedResp {
	return &VideoFeedResp{}
}

func (p *VideoFeedResp) InitDefault() {
	*p = VideoFeedResp{}
}

var VideoFeedResp_Count_DEFAULT int32

func (p *VideoFeedResp) GetCount() (v int32) {
	if !p.IsSetCount() {
		return VideoFeedResp_Count_DEFAULT
	}
	return *p.Count
}

var VideoFeedResp_Items_DEFAULT []*VideoInfo

func (p *VideoFeedResp) GetItems() (v []*VideoInfo) {
	if !p.IsSetItems() {
		return VideoFeedResp_Items_DEFAULT
	}
	return p.Items
}
func (p *VideoFeedResp) SetCount(val *int32) {
	p.Count = val
}
func (p *VideoFeedResp) SetItems(val []*VideoInfo) {
	p.Items = val
}

var fieldIDToName_VideoFeedResp = map[int16]string{
	1: "Count",
	2: "items",
}

func (p *VideoFeedResp) IsSetCount() bool {
	return p.Count != nil
}

func (p *VideoFeedResp) IsSetItems() bool {
	return p.Items != nil
}

func (p *VideoFeedResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_VideoFeedResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *VideoFeedResp) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Count = &v
	}
	return nil
}
func (p *VideoFeedResp) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.Items = make([]*VideoInfo, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewVideoInfo()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.Items = append(p.Items, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}

func (p *VideoFeedResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("VideoFeedResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *VideoFeedResp) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetCount() {
		if err = oprot.WriteFieldBegin("Count", thrift.I32, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Count); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *VideoFeedResp) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetItems() {
		if err = oprot.WriteFieldBegin("items", thrift.LIST, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Items)); err != nil {
			return err
		}
		for _, v := range p.Items {
			if err := v.Write(oprot); err != nil {
				return err
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *VideoFeedResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoFeedResp(%+v)", *p)

}

func (p *VideoFeedResp) DeepEqual(ano *VideoFeedResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Count) {
		return false
	}
	if !p.Field2DeepEqual(ano.Items) {
		return false
	}
	return true
}

func (p *VideoFeedResp) Field1DeepEqual(src *int32) bool {

	if p.Count == src {
		return true
	} else if p.Count == nil || src == nil {
		return false
	}
	if *p.Count != *src {
		return false
	}
	return true
}
func (p *VideoFeedResp) Field2DeepEqual(src []*VideoInfo) bool {

	if len(p.Items) != len(src) {
		return false
	}
	for i, v := range p.Items {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type PublishVideoReq struct {
	Intro *string `thrift:"Intro,1,optional" frugal:"1,optional,string" form:"intro,required"`
	Title *string `thrift:"Title,2,optional" frugal:"2,optional,string" form:"title,required"`
	Video []byte  `thrift:"Video,3,optional" frugal:"3,optional,binary" form:"video_content,required"`
	Cover []byte  `thrift:"cover,4,optional" frugal:"4,optional,binary" form:"cover,required"`
	UID   *int64  `thrift:"UID,5,optional" frugal:"5,optional,i64" json:"UID,omitempty"`
}

func NewPublishVideoReq() *PublishVideoReq {
	return &PublishVideoReq{}
}

func (p *PublishVideoReq) InitDefault() {
	*p = PublishVideoReq{}
}

var PublishVideoReq_Intro_DEFAULT string

func (p *PublishVideoReq) GetIntro() (v string) {
	if !p.IsSetIntro() {
		return PublishVideoReq_Intro_DEFAULT
	}
	return *p.Intro
}

var PublishVideoReq_Title_DEFAULT string

func (p *PublishVideoReq) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return PublishVideoReq_Title_DEFAULT
	}
	return *p.Title
}

var PublishVideoReq_Video_DEFAULT []byte

func (p *PublishVideoReq) GetVideo() (v []byte) {
	if !p.IsSetVideo() {
		return PublishVideoReq_Video_DEFAULT
	}
	return p.Video
}

var PublishVideoReq_Cover_DEFAULT []byte

func (p *PublishVideoReq) GetCover() (v []byte) {
	if !p.IsSetCover() {
		return PublishVideoReq_Cover_DEFAULT
	}
	return p.Cover
}

var PublishVideoReq_UID_DEFAULT int64

func (p *PublishVideoReq) GetUID() (v int64) {
	if !p.IsSetUID() {
		return PublishVideoReq_UID_DEFAULT
	}
	return *p.UID
}
func (p *PublishVideoReq) SetIntro(val *string) {
	p.Intro = val
}
func (p *PublishVideoReq) SetTitle(val *string) {
	p.Title = val
}
func (p *PublishVideoReq) SetVideo(val []byte) {
	p.Video = val
}
func (p *PublishVideoReq) SetCover(val []byte) {
	p.Cover = val
}
func (p *PublishVideoReq) SetUID(val *int64) {
	p.UID = val
}

var fieldIDToName_PublishVideoReq = map[int16]string{
	1: "Intro",
	2: "Title",
	3: "Video",
	4: "cover",
	5: "UID",
}

func (p *PublishVideoReq) IsSetIntro() bool {
	return p.Intro != nil
}

func (p *PublishVideoReq) IsSetTitle() bool {
	return p.Title != nil
}

func (p *PublishVideoReq) IsSetVideo() bool {
	return p.Video != nil
}

func (p *PublishVideoReq) IsSetCover() bool {
	return p.Cover != nil
}

func (p *PublishVideoReq) IsSetUID() bool {
	return p.UID != nil
}

func (p *PublishVideoReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PublishVideoReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PublishVideoReq) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Intro = &v
	}
	return nil
}
func (p *PublishVideoReq) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Title = &v
	}
	return nil
}
func (p *PublishVideoReq) ReadField3(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadBinary(); err != nil {
		return err
	} else {
		p.Video = []byte(v)
	}
	return nil
}
func (p *PublishVideoReq) ReadField4(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadBinary(); err != nil {
		return err
	} else {
		p.Cover = []byte(v)
	}
	return nil
}
func (p *PublishVideoReq) ReadField5(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.UID = &v
	}
	return nil
}

func (p *PublishVideoReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("PublishVideoReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PublishVideoReq) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIntro() {
		if err = oprot.WriteFieldBegin("Intro", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Intro); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PublishVideoReq) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetTitle() {
		if err = oprot.WriteFieldBegin("Title", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Title); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PublishVideoReq) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetVideo() {
		if err = oprot.WriteFieldBegin("Video", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteBinary([]byte(p.Video)); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *PublishVideoReq) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCover() {
		if err = oprot.WriteFieldBegin("cover", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteBinary([]byte(p.Cover)); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *PublishVideoReq) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetUID() {
		if err = oprot.WriteFieldBegin("UID", thrift.I64, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.UID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *PublishVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoReq(%+v)", *p)

}

func (p *PublishVideoReq) DeepEqual(ano *PublishVideoReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Intro) {
		return false
	}
	if !p.Field2DeepEqual(ano.Title) {
		return false
	}
	if !p.Field3DeepEqual(ano.Video) {
		return false
	}
	if !p.Field4DeepEqual(ano.Cover) {
		return false
	}
	if !p.Field5DeepEqual(ano.UID) {
		return false
	}
	return true
}

func (p *PublishVideoReq) Field1DeepEqual(src *string) bool {

	if p.Intro == src {
		return true
	} else if p.Intro == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Intro, *src) != 0 {
		return false
	}
	return true
}
func (p *PublishVideoReq) Field2DeepEqual(src *string) bool {

	if p.Title == src {
		return true
	} else if p.Title == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Title, *src) != 0 {
		return false
	}
	return true
}
func (p *PublishVideoReq) Field3DeepEqual(src []byte) bool {

	if bytes.Compare(p.Video, src) != 0 {
		return false
	}
	return true
}
func (p *PublishVideoReq) Field4DeepEqual(src []byte) bool {

	if bytes.Compare(p.Cover, src) != 0 {
		return false
	}
	return true
}
func (p *PublishVideoReq) Field5DeepEqual(src *int64) bool {

	if p.UID == src {
		return true
	} else if p.UID == nil || src == nil {
		return false
	}
	if *p.UID != *src {
		return false
	}
	return true
}

type PublishVideoResp struct {
}

func NewPublishVideoResp() *PublishVideoResp {
	return &PublishVideoResp{}
}

func (p *PublishVideoResp) InitDefault() {
	*p = PublishVideoResp{}
}

var fieldIDToName_PublishVideoResp = map[int16]string{}

func (p *PublishVideoResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err = iprot.Skip(fieldTypeId); err != nil {
			goto SkipFieldTypeError
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
SkipFieldTypeError:
	return thrift.PrependError(fmt.Sprintf("%T skip field type %d error", p, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PublishVideoResp) Write(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteStructBegin("PublishVideoResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PublishVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoResp(%+v)", *p)

}

func (p *PublishVideoResp) DeepEqual(ano *PublishVideoResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

type GetVideoListReq struct {
	UID   *int64 `thrift:"UID,1,optional" frugal:"1,optional,i64" json:"UID,omitempty"`
	Pages *int32 `thrift:"Pages,2,optional" frugal:"2,optional,i32" form:"pages,required"`
	Size  *int8  `thrift:"Size,3,optional" frugal:"3,optional,i8" form:"pages,required"`
}

func NewGetVideoListReq() *GetVideoListReq {
	return &GetVideoListReq{}
}

func (p *GetVideoListReq) InitDefault() {
	*p = GetVideoListReq{}
}

var GetVideoListReq_UID_DEFAULT int64

func (p *GetVideoListReq) GetUID() (v int64) {
	if !p.IsSetUID() {
		return GetVideoListReq_UID_DEFAULT
	}
	return *p.UID
}

var GetVideoListReq_Pages_DEFAULT int32

func (p *GetVideoListReq) GetPages() (v int32) {
	if !p.IsSetPages() {
		return GetVideoListReq_Pages_DEFAULT
	}
	return *p.Pages
}

var GetVideoListReq_Size_DEFAULT int8

func (p *GetVideoListReq) GetSize() (v int8) {
	if !p.IsSetSize() {
		return GetVideoListReq_Size_DEFAULT
	}
	return *p.Size
}
func (p *GetVideoListReq) SetUID(val *int64) {
	p.UID = val
}
func (p *GetVideoListReq) SetPages(val *int32) {
	p.Pages = val
}
func (p *GetVideoListReq) SetSize(val *int8) {
	p.Size = val
}

var fieldIDToName_GetVideoListReq = map[int16]string{
	1: "UID",
	2: "Pages",
	3: "Size",
}

func (p *GetVideoListReq) IsSetUID() bool {
	return p.UID != nil
}

func (p *GetVideoListReq) IsSetPages() bool {
	return p.Pages != nil
}

func (p *GetVideoListReq) IsSetSize() bool {
	return p.Size != nil
}

func (p *GetVideoListReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.BYTE {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetVideoListReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetVideoListReq) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.UID = &v
	}
	return nil
}
func (p *GetVideoListReq) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Pages = &v
	}
	return nil
}
func (p *GetVideoListReq) ReadField3(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadByte(); err != nil {
		return err
	} else {
		p.Size = &v
	}
	return nil
}

func (p *GetVideoListReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetVideoListReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetVideoListReq) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetUID() {
		if err = oprot.WriteFieldBegin("UID", thrift.I64, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.UID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetVideoListReq) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetPages() {
		if err = oprot.WriteFieldBegin("Pages", thrift.I32, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Pages); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *GetVideoListReq) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetSize() {
		if err = oprot.WriteFieldBegin("Size", thrift.BYTE, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteByte(*p.Size); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *GetVideoListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoListReq(%+v)", *p)

}

func (p *GetVideoListReq) DeepEqual(ano *GetVideoListReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.UID) {
		return false
	}
	if !p.Field2DeepEqual(ano.Pages) {
		return false
	}
	if !p.Field3DeepEqual(ano.Size) {
		return false
	}
	return true
}

func (p *GetVideoListReq) Field1DeepEqual(src *int64) bool {

	if p.UID == src {
		return true
	} else if p.UID == nil || src == nil {
		return false
	}
	if *p.UID != *src {
		return false
	}
	return true
}
func (p *GetVideoListReq) Field2DeepEqual(src *int32) bool {

	if p.Pages == src {
		return true
	} else if p.Pages == nil || src == nil {
		return false
	}
	if *p.Pages != *src {
		return false
	}
	return true
}
func (p *GetVideoListReq) Field3DeepEqual(src *int8) bool {

	if p.Size == src {
		return true
	} else if p.Size == nil || src == nil {
		return false
	}
	if *p.Size != *src {
		return false
	}
	return true
}

type GetVideoListResp struct {
	Count *int32       `thrift:"Count,1,optional" frugal:"1,optional,i32" json:"count,omitempty"`
	Items []*VideoInfo `thrift:"items,2,optional" frugal:"2,optional,list<VideoInfo>" json:"items,omitempry"`
}

func NewGetVideoListResp() *GetVideoListResp {
	return &GetVideoListResp{}
}

func (p *GetVideoListResp) InitDefault() {
	*p = GetVideoListResp{}
}

var GetVideoListResp_Count_DEFAULT int32

func (p *GetVideoListResp) GetCount() (v int32) {
	if !p.IsSetCount() {
		return GetVideoListResp_Count_DEFAULT
	}
	return *p.Count
}

var GetVideoListResp_Items_DEFAULT []*VideoInfo

func (p *GetVideoListResp) GetItems() (v []*VideoInfo) {
	if !p.IsSetItems() {
		return GetVideoListResp_Items_DEFAULT
	}
	return p.Items
}
func (p *GetVideoListResp) SetCount(val *int32) {
	p.Count = val
}
func (p *GetVideoListResp) SetItems(val []*VideoInfo) {
	p.Items = val
}

var fieldIDToName_GetVideoListResp = map[int16]string{
	1: "Count",
	2: "items",
}

func (p *GetVideoListResp) IsSetCount() bool {
	return p.Count != nil
}

func (p *GetVideoListResp) IsSetItems() bool {
	return p.Items != nil
}

func (p *GetVideoListResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetVideoListResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetVideoListResp) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Count = &v
	}
	return nil
}
func (p *GetVideoListResp) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.Items = make([]*VideoInfo, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewVideoInfo()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.Items = append(p.Items, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}

func (p *GetVideoListResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetVideoListResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetVideoListResp) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetCount() {
		if err = oprot.WriteFieldBegin("Count", thrift.I32, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Count); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetVideoListResp) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetItems() {
		if err = oprot.WriteFieldBegin("items", thrift.LIST, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Items)); err != nil {
			return err
		}
		for _, v := range p.Items {
			if err := v.Write(oprot); err != nil {
				return err
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *GetVideoListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoListResp(%+v)", *p)

}

func (p *GetVideoListResp) DeepEqual(ano *GetVideoListResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Count) {
		return false
	}
	if !p.Field2DeepEqual(ano.Items) {
		return false
	}
	return true
}

func (p *GetVideoListResp) Field1DeepEqual(src *int32) bool {

	if p.Count == src {
		return true
	} else if p.Count == nil || src == nil {
		return false
	}
	if *p.Count != *src {
		return false
	}
	return true
}
func (p *GetVideoListResp) Field2DeepEqual(src []*VideoInfo) bool {

	if len(p.Items) != len(src) {
		return false
	}
	for i, v := range p.Items {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type GetVideoPupularReq struct {
	VID *int64 `thrift:"VID,1,optional" frugal:"1,optional,i64" form:"vid,required"`
}

func NewGetVideoPupularReq() *GetVideoPupularReq {
	return &GetVideoPupularReq{}
}

func (p *GetVideoPupularReq) InitDefault() {
	*p = GetVideoPupularReq{}
}

var GetVideoPupularReq_VID_DEFAULT int64

func (p *GetVideoPupularReq) GetVID() (v int64) {
	if !p.IsSetVID() {
		return GetVideoPupularReq_VID_DEFAULT
	}
	return *p.VID
}
func (p *GetVideoPupularReq) SetVID(val *int64) {
	p.VID = val
}

var fieldIDToName_GetVideoPupularReq = map[int16]string{
	1: "VID",
}

func (p *GetVideoPupularReq) IsSetVID() bool {
	return p.VID != nil
}

func (p *GetVideoPupularReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetVideoPupularReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetVideoPupularReq) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.VID = &v
	}
	return nil
}

func (p *GetVideoPupularReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetVideoPupularReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetVideoPupularReq) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetVID() {
		if err = oprot.WriteFieldBegin("VID", thrift.I64, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.VID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetVideoPupularReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoPupularReq(%+v)", *p)

}

func (p *GetVideoPupularReq) DeepEqual(ano *GetVideoPupularReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.VID) {
		return false
	}
	return true
}

func (p *GetVideoPupularReq) Field1DeepEqual(src *int64) bool {

	if p.VID == src {
		return true
	} else if p.VID == nil || src == nil {
		return false
	}
	if *p.VID != *src {
		return false
	}
	return true
}

type GetVideoPopularResp struct {
	FavoriteCount *int32 `thrift:"FavoriteCount,1,optional" frugal:"1,optional,i32" json:"favorite_count,omitempry"`
}

func NewGetVideoPopularResp() *GetVideoPopularResp {
	return &GetVideoPopularResp{}
}

func (p *GetVideoPopularResp) InitDefault() {
	*p = GetVideoPopularResp{}
}

var GetVideoPopularResp_FavoriteCount_DEFAULT int32

func (p *GetVideoPopularResp) GetFavoriteCount() (v int32) {
	if !p.IsSetFavoriteCount() {
		return GetVideoPopularResp_FavoriteCount_DEFAULT
	}
	return *p.FavoriteCount
}
func (p *GetVideoPopularResp) SetFavoriteCount(val *int32) {
	p.FavoriteCount = val
}

var fieldIDToName_GetVideoPopularResp = map[int16]string{
	1: "FavoriteCount",
}

func (p *GetVideoPopularResp) IsSetFavoriteCount() bool {
	return p.FavoriteCount != nil
}

func (p *GetVideoPopularResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetVideoPopularResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetVideoPopularResp) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.FavoriteCount = &v
	}
	return nil
}

func (p *GetVideoPopularResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetVideoPopularResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetVideoPopularResp) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetFavoriteCount() {
		if err = oprot.WriteFieldBegin("FavoriteCount", thrift.I32, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.FavoriteCount); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetVideoPopularResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoPopularResp(%+v)", *p)

}

func (p *GetVideoPopularResp) DeepEqual(ano *GetVideoPopularResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.FavoriteCount) {
		return false
	}
	return true
}

func (p *GetVideoPopularResp) Field1DeepEqual(src *int32) bool {

	if p.FavoriteCount == src {
		return true
	} else if p.FavoriteCount == nil || src == nil {
		return false
	}
	if *p.FavoriteCount != *src {
		return false
	}
	return true
}

type SearchVideoReq struct {
	Content *string `thrift:"content,1,optional" frugal:"1,optional,string" form:"content,required"`
}

func NewSearchVideoReq() *SearchVideoReq {
	return &SearchVideoReq{}
}

func (p *SearchVideoReq) InitDefault() {
	*p = SearchVideoReq{}
}

var SearchVideoReq_Content_DEFAULT string

func (p *SearchVideoReq) GetContent() (v string) {
	if !p.IsSetContent() {
		return SearchVideoReq_Content_DEFAULT
	}
	return *p.Content
}
func (p *SearchVideoReq) SetContent(val *string) {
	p.Content = val
}

var fieldIDToName_SearchVideoReq = map[int16]string{
	1: "content",
}

func (p *SearchVideoReq) IsSetContent() bool {
	return p.Content != nil
}

func (p *SearchVideoReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SearchVideoReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SearchVideoReq) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Content = &v
	}
	return nil
}

func (p *SearchVideoReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("SearchVideoReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SearchVideoReq) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetContent() {
		if err = oprot.WriteFieldBegin("content", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Content); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SearchVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchVideoReq(%+v)", *p)

}

func (p *SearchVideoReq) DeepEqual(ano *SearchVideoReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Content) {
		return false
	}
	return true
}

func (p *SearchVideoReq) Field1DeepEqual(src *string) bool {

	if p.Content == src {
		return true
	} else if p.Content == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Content, *src) != 0 {
		return false
	}
	return true
}

type SearchVideoResp struct {
	Count *int32       `thrift:"Count,1,optional" frugal:"1,optional,i32" json:"count,omitempry"`
	Items []*VideoInfo `thrift:"items,2,optional" frugal:"2,optional,list<VideoInfo>" json:"items,omitempry"`
}

func NewSearchVideoResp() *SearchVideoResp {
	return &SearchVideoResp{}
}

func (p *SearchVideoResp) InitDefault() {
	*p = SearchVideoResp{}
}

var SearchVideoResp_Count_DEFAULT int32

func (p *SearchVideoResp) GetCount() (v int32) {
	if !p.IsSetCount() {
		return SearchVideoResp_Count_DEFAULT
	}
	return *p.Count
}

var SearchVideoResp_Items_DEFAULT []*VideoInfo

func (p *SearchVideoResp) GetItems() (v []*VideoInfo) {
	if !p.IsSetItems() {
		return SearchVideoResp_Items_DEFAULT
	}
	return p.Items
}
func (p *SearchVideoResp) SetCount(val *int32) {
	p.Count = val
}
func (p *SearchVideoResp) SetItems(val []*VideoInfo) {
	p.Items = val
}

var fieldIDToName_SearchVideoResp = map[int16]string{
	1: "Count",
	2: "items",
}

func (p *SearchVideoResp) IsSetCount() bool {
	return p.Count != nil
}

func (p *SearchVideoResp) IsSetItems() bool {
	return p.Items != nil
}

func (p *SearchVideoResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SearchVideoResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SearchVideoResp) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Count = &v
	}
	return nil
}
func (p *SearchVideoResp) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.Items = make([]*VideoInfo, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewVideoInfo()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.Items = append(p.Items, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}

func (p *SearchVideoResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("SearchVideoResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SearchVideoResp) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetCount() {
		if err = oprot.WriteFieldBegin("Count", thrift.I32, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Count); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SearchVideoResp) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetItems() {
		if err = oprot.WriteFieldBegin("items", thrift.LIST, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Items)); err != nil {
			return err
		}
		for _, v := range p.Items {
			if err := v.Write(oprot); err != nil {
				return err
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *SearchVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchVideoResp(%+v)", *p)

}

func (p *SearchVideoResp) DeepEqual(ano *SearchVideoResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Count) {
		return false
	}
	if !p.Field2DeepEqual(ano.Items) {
		return false
	}
	return true
}

func (p *SearchVideoResp) Field1DeepEqual(src *int32) bool {

	if p.Count == src {
		return true
	} else if p.Count == nil || src == nil {
		return false
	}
	if *p.Count != *src {
		return false
	}
	return true
}
func (p *SearchVideoResp) Field2DeepEqual(src []*VideoInfo) bool {

	if len(p.Items) != len(src) {
		return false
	}
	for i, v := range p.Items {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
