apiVersion: v1
kind: Service
metadata:
  name: tiktok-relation-svc
spec:
  type: NodePort
  selector:
    app: tiktok-relation-pod
  ports:
    - protocol: TCP
      port: 10004
      targetPort: 10004
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-relation-dep
spec:
  selector:
    matchLabels:
      app: tiktok-relation-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: tiktok-relation-pod
    spec:
      containers:
        - name: service-relation
          image: mutezebra/tiktok-relation:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10004
          volumeMounts:
            - name: config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: config
          configMap:
            name: tiktok-relation-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: logs
          persistentVolumeClaim:
            claimName: tiktok-relation-log-pvc
